# Generated by Django 5.0.1 on 2024-01-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars/'),
        ),
    ]
