# Generated by Django 5.0.1 on 2024-01-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, default=None, upload_to="avatars/"),
        ),
    ]
