# Generated by Django 5.0.1 on 2024-01-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_dalleimage_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dalleimage",
            name="image",
            field=models.ImageField(
                upload_to="generated_images/", verbose_name="Generated Image"
            ),
        ),
    ]
