# Generated by Django 5.0.1 on 2024-01-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_delete_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_flyer',
            field=models.ImageField(default=None, upload_to='event_flyers/', verbose_name='Event Flyer'),
        ),
    ]
