# Generated by Django 5.0.2 on 2024-02-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0027_event_event_type_event_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fav_artist",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.artist",
            ),
        ),
    ]
