# Generated by Django 5.0.2 on 2024-02-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_profile_fav_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_artist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.artist', verbose_name='Favorite Artist'),
        ),
    ]
