# Generated by Django 5.0.2 on 2024-03-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0033_alter_profile_fav_genre"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DallEImage",
        ),
    ]
