MUSIC_GENRES_CHOICES = [
    ("rock", "Rock"),
    ("pop", "Pop"),
    ("hip_hop", "Hip Hop"),
    ("electronic", "Electronic"),
    ("jazz", "Jazz"),
    ("blues", "Blues"),
    ("country", "Country"),
    ("classical", "Classical"),
    ("reggae", "Reggae"),
    ("metal", "Metal"),
    ("folk", "Folk"),
    ("rnb", "R&B"),
    ("indie", "Indie"),
    ("punk", "Punk"),
    ("soul", "Soul"),
    ("funk", "Funk"),
    ("techno", "Techno"),
    ("disco", "Disco"),
    ("ambient", "Ambient"),
    ("reggaeton", "Reggaeton"),
    ("ska", "Ska"),
    ("gospel", "Gospel"),
    ("trance", "Trance"),
    ("dancehall", "Dancehall"),
    ("opera", "Opera"),
]
